# -*- coding: utf-8 -*-
"""Logistic Regression_AirlinesData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rz-EBabyzx9oaq5_5qseGzcXtUJKYGHV
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/AI ML Bootcamp/Week 1/Invistico_Airline.csv')

df.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df.isnull().sum()

newdf = df.dropna()

newdf.isnull().sum()

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer()

from sklearn.preprocessing import LabelEncoder
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column].astype(str))

imputer = IterativeImputer()
newdf1 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

newdf1.isnull().sum()

new_df1 = imputer.fit_transform(df)

new_df1 = pd.DataFrame(new_df1, columns=df.columns)

new_df1.isnull().sum()

X = new_df1.drop('Arrival Delay in Minutes', axis=1)
y = new_df1['Arrival Delay in Minutes']

df['Delay_Category'] = df['Arrival Delay in Minutes'].apply(lambda x: 1 if x > 0 else 0)
X = df.drop(['Arrival Delay in Minutes', 'Delay_Category'], axis=1)
y = df['Delay_Category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)
class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)